# Generated by Django 3.2.12 on 2022-03-31 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pages', '0001_initial'), ('pages', '0002_auto_20220330_1716'), ('pages', '0003_page_title'), ('pages', '0004_auto_20220330_1530'), ('pages', '0005_alter_contentpiece_counter'), ('pages', '0006_alter_contentpiece_counter'), ('pages', '0007_auto_20220330_2218'), ('pages', '0008_auto_20220331_0502')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('counter', models.PositiveIntegerField(blank=True, default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_pages.contentpiece_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'unique_together': {('title', 'polymorphic_ctype_id')},
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AudioPiece',
            fields=[
                ('contentpiece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.contentpiece')),
                ('bitrate', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pages.contentpiece',),
        ),
        migrations.CreateModel(
            name='TextPiece',
            fields=[
                ('contentpiece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.contentpiece')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pages.contentpiece',),
        ),
        migrations.CreateModel(
            name='VideoPiece',
            fields=[
                ('contentpiece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.contentpiece')),
                ('video_url', models.URLField()),
                ('subtitles_url', models.URLField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pages.contentpiece',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PieceOnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contentpiece')),
                ('piece_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['piece_order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='pieces',
            field=models.ManyToManyField(through='pages.PieceOnPage', to='pages.ContentPiece'),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-id']},
        ),
    ]
