# Generated by Django 3.2.12 on 2022-03-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceOnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contentpiece')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='pieces',
        ),
        migrations.AddField(
            model_name='page',
            name='pieces',
            field=models.ManyToManyField(through='pages.PieceOnPage', to='pages.ContentPiece'),
        ),
    ]
