# Generated by Django 3.2.12 on 2022-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_contentpiece_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpiece',
            name='counter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
