version: '3.8'

services:
  runserver:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  celery_worker:
    build: .
    command: celery --app=config worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.dev
    depends_on:
      - runserver
      - redis
  redis:
    image: redis
  celery_flower:
    build: .
    command: celery --app=config --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    env_file:
      - .env.dev
    depends_on:
      - runserver
      - redis
      - celery_worker
  autotests:
    build: .
    command: python manage.py test app
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  postgres_data:
